services:
  - type: web
    name: o-supreme-burger
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PUBLIC_URL
        sync: false
